name 'ericsson-sendmail'
version '0.1.0'
source 'git://github.com/Ericsson/puppet-module-sendmail.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Module to manage sendmail'
description 'Module to manage sendmail on Solaris'
project_page 'https://github.com/Ericsson/puppet-module-sendmail'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
